### ISSUE TITLE
myContract.getPastEvents('allEvents') seems to not support filter options

### ISSUE THREAD

**Issue by vrolland** [ethereum/web3.js#1219]
Hello guys,

The filter doesn't work with "getPastEvents" when the first parameter is "allEvents".
It returns me all the events whatever the filter.

Would be great to be able to select all the event types and filter them with indexed parameters.

Best,

**Comment by davodesign84** [comment]
Same for me, just stumbled on the same issue.

According to the docs it sounds like it should be supported http://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#getpastevents

**Comment by atomixxx2** [comment]
Same issue here, using 1.0.0.beta30, filter is not being considered, both with and without "allEvents"

**Comment by bshevchenko** [comment]
Same for 1.0.0.beta33

**Comment by bshevchenko** [comment]
From getPastEvents docs:
*filter - Object (optional): Lets you filter events by indexed parameters*
My param is not indexed, so probably solution is found for me

**Comment by bshevchenko** [comment]
@vrolland @davodesign84 @atomixxx2 use indexed and it'll work

**Comment by atomixxx2** [comment]
Hi @bshevchenko, Im already using indexed event fields, it is not working.

**Comment by nivida** [comment]
@alejoloaiza Please give us some more informations :)

**Comment by vrolland** [comment]
@bshevchenko I used indexed parameters.

@nivida The filter works when I am getting a specific event but not when I am using the generic "allEvents". 
For example with the following event:
`event Created(bytes32 indexed identifier);`

Here the filter is not taking in account:
```
await instanceContract.getPastEvents('allEvents', {
    filter: {identifier: value}
});
```

Here, the filter works:
```
await instanceContract.getPastEvents('Created', {
    filter: {identifier: value}
});
```

Is it clearer?

**Comment by nivida** [comment]
This got fixed in the [``AbstractContract``](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-eth-contract/src/AbstractContract.js#L174) object during the refactoring.

**Comment by przemyslawlukasz** [comment]
Seems like this still doesn't work

**Comment by boyuanx** [comment]
It still doesn't work on web3 1.2.11, bumping this @nivida .

**Comment by sirpy** [comment]
not working on 2.0.0 this should be opened
@nivida

**Comment by aligilani1986** [comment]
It still does not work on web3 latest version (1.8.2).
Why?
