### ISSUE TITLE
Invalid Websocket headers in 1.0.0-beta.34

### ISSUE THREAD

**Issue by Matko95** [ethereum/web3.js#1559]
So the issue came when updating to 1.0.0-beta.34 version, the websocket connection fails to a parity node with the following error. 

`WebSocket connection to 'wss://kovan.decenter.com:4443/' failed: Error during WebSocket handshake: Unexpected response code: 403`

The issue is that in the request headers we have value of `Sec-WebSocket-Protocol: undefined` which gets handled badly on the node since it's undefined. Reverting the version to 1.0.0-beta.33 fixes the issue.

`
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,sr-RS;q=0.8,sr;q=0.7
Cache-Control: no-cache
Connection: Upgrade
DNT: 1
Host: kovan.decenter.com:4443
Origin: http://127.0.0.1:8080
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: l+ZG48eY3Nt11jph4pXlYA==
Sec-WebSocket-Protocol: undefined
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
`

**Comment by amaurymartiny** [comment]
Confirmed.

**Comment by frozeman** [comment]
Should be fixed in the next release.

**Comment by wodxumingxu** [comment]
I tried the 1.0.0-beta.35, still not working and the same issue. the 1.0.0-beta.33 works

**Comment by Mischi** [comment]
It will be available in 1.0.0-beta.36

wodxumingxu <notifications@github.com> schrieb am So., 12. Aug. 2018, 16:54:

**Comment by frozeman** [comment]
The next release will be .36 try the 1.0 branch please.

**Comment by wodxumingxu** [comment]
thank you guys for the clarification
