### ISSUE TITLE
Node.js: myContract.events subscription using options throws error

### ISSUE THREAD

**Issue by Mozeps** [ethereum/web3.js#2604]
### Description 
When subscribing to an event of a contract deployed to a ganache blockchain-client, trying to use options such as "fromBlock" throws an error. The syntax follows the example of the web3 docs (https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#id38).

The error occurence does not depend on "how" you subscribe to the event, it occurs if you are subscribing through the signature as well as trough the event name.

The error depends on using the ".events" syntax, it does not occur when using myContract.getPastEvents.

#### Expected behavior
```
myContract.events[
        "0x131651a9ef17e0a6963ff90cb2e0d1007110861a27cec93815590ae0bb418e69"
      ](
        {
          fromBlock: 0
        },
        (error, event) => {
          if (error) {
            console.error("subscription error:", error);
          } else {
            console.log("successfully caught event");
          }
        }
  );
```
Executing this code should print the "successfully caught event" message multiple times to the console.

#### Actual behavior

Following error message is printed:
`subscription error: TypeError: Cannot read property 'currentProvider' of undefined`

If i make the following change (commenting fromBlock) the subscription works:
```
myContract.events[
        "0x131651a9ef17e0a6963ff90cb2e0d1007110861a27cec93815590ae0bb418e69"
      ](
        {
          //fromBlock: 0
        },
        (error, event) => {
          if (error) {
            console.error("subscription error:", error);
          } else {
            console.log("successfully caught event");
          }
        }
  );
```

#### Steps to reproduce the behavior
1. Run Ganache
2. Deploy a contract similar to the following: 
```
pragma solidity ^0.5.0;

contract SubContract1 {

  bytes32 public state;

  event SomethingHappened(
    bytes32 name
  );

  constructor() public {
      state = stateOne;
  }

  bytes32 stateOne = "state one";
  bytes32 stateTwo = "state two";
  bytes32 finishedText = "Finished doing something";

  function doSomething() public {
    if(state == stateOne) {
        state = stateTwo;
    } else {
        state = stateOne;
    }
    emit SomethingHappened(finishedText);
  }
}
```

3. Initialize web3 in Node.js like so:
`let web3 = new Web3.providers.WebsocketProvider("ws://localhost:8545");`
4. Initialize the contract in Node.js like so:
`let myContract = new web3.eth.Contract(abi, address);`
5. Run subscription code shown in the beginning.

#### Error Logs 
```
subscription error: TypeError: Cannot read property 'currentProvider' of undefined
    at GetPastLogsMethod._callee$ (C:\web3Test\node_modules\web3-core-method\dist\web3-core-method.cjs.js:97:44)
    at tryCatch (C:\web3Test\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\web3Test\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (C:\web3Test\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:114:21)
    at asyncGeneratorStep (C:\web3Test\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\web3Test\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\web3Test\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GetPastLogsMethod.<anonymous> (C:\web3Test\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GetPastLogsMethod.execute (C:\web3Test\node_modules\web3-core-method\dist\web3-core-method.cjs.js:122:25)
    at EventLogSubscription.subscribe (C:\web3Test\node_modules\web3-core-subscriptions\dist\web3-core-subscriptions.cjs.js:106:32)
    at EventSubscriptionsProxy.subscribe (C:\web3Test\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:599:189)
    at Proxy.<anonymous> (C:\web3Test\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:580:27)
    at SubscriptionTest._subscribeToContractEvents (C:\web3Test\src\SubscriptionTest\SubscriptionTest.js:131:8)
    at SubscriptionTest.main (C:\web3Test\src\SubscriptionTest\SubscriptionTest.js:31:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Versions 
* web3.js: 1.0.0-beta.50
UPDATE: Same error with web3 version 1.0.0-beta.51
* nodejs: v10.15.0
* ganache: v2.0.0

**Comment by nivida** [comment]
This got fixed with version 1.0.0-beta.51.

**Comment by Mozeps** [comment]
For everybody running through the same issue, the bug is not fixed yet. Though there is another issue regarding the bug: #2611.
