### ISSUE TITLE
Not getting success callback/ receipt with walletconnect with web3.js 1.3.3

### ISSUE THREAD

**Issue by imaksp** [ethereum/web3.js#3891]
#### Expected behavior
- It should give success callback & receipt if used with WalletConnect

#### Actual behavior
- After 1.3.x update (tried with 1.3.3 & 1.3.4 rc.1), it is working upto below callback
```js
.on('transactionHash', function(hash){
    ...
}) 
```
on 'receipt' OR below one
```js
.then(function(receipt){
    // receipt can also be a new contract instance, when coming from a "contract.deploy({...}).send()"
});
```
 Never gets called but it is working fine with web3.js 1.2.11.

#### Steps to reproduce the behavior

1. Connect wallet by scanning QR code with Metamask mobile or WalletConnect supported wallet app
2. Do any contract interaction Txn (using myMethod(123).send) 
3. See if its calling final success callback with receipt

#### Environment
WalletConnect web3 provider:  tried 1.3.1 & current latest 1.3.4
Node: 14.15.x
web3.js: 1.3.3 & 1.3.4.rc1
OS: Mac OS 11.1

If possible please release new 1.2.x version with Metamask hotfix, if it can't be fixed quickly with 1.3.x

**Comment by GregTheGreek** [comment]
By chance do you have a demo app?

**Comment by imaksp** [comment]
No I don't have demo app, let me know if it is required, will make it tomorrow.

**Comment by Spacesai1or** [comment]
For a sanity check, I tested this locally using `ganache-cli` by deploying the `SimpleStorage.sol` contract and submitted a `set` transaction - I received the `transactionHash`, the `receipt`, and the `confirmation` events

**Comment by Spacesai1or** [comment]
> No I don't have demo app, let me know if it is required, will make it tomorrow.

If you could provide a demo app, it would help debugging tremendously

**Comment by imaksp** [comment]
@spacesailor24 Ok will try to make demo, btw I tried approve method of ERC20 contract & wallet was connected using metamask mobile app on Android using Walletconnect QR code, on rinkeby test network.

Btw it is working as expected with metamask browser extension but not with Walletconnect so we downgraded app to 1.2.11.

**Comment by ujal** [comment]
I am having the same issue with ganache-cli. The contract deploys but the transactionHash is always undefined. The then callback is never called too. The issue is happening on web3-eth-contract@1.3.4.

**Comment by imaksp** [comment]
@spacesailor24 Hi, here is the demo app for the issue, please see README for steps, don't forget to set 'REACT_APP_INFURA_ID' in '.env' before connecting.
Demo link: https://github.com/aksdevac/wc-web3-demo

**Comment by Spacesai1or** [comment]
> I am having the same issue with ganache-cli. The contract deploys but the transactionHash is always undefined. The then callback is never called too. The issue is happening on web3-eth-contract@1.3.4.

Could you provide a code snippet of what's not working? I can do the same for code that was working using ganache-cli

**Comment by Spacesai1or** [comment]
Forgot to @ujal ^

**Comment by Spacesai1or** [comment]
> @spacesailor24 Hi, here is the demo app for the issue, please see README for steps, don't forget to set 'REACT_APP_INFURA_ID' in '.env' before connecting.
> 
> Demo link: https://github.com/aksdevac/wc-web3-demo 

Awesome, thank you! I'll be taking a look at this shortly

**Comment by ujal** [comment]
@spacesailor24 
```javascript
contract.deploy({ data: bytecode }).send({ from: account }, function(err, transactionHash) {
  console.log(transactionHash)
}).then(function(newContract) {
  console.log(newContract.options.address)
});
```

**Comment by Spacesai1or** [comment]
@ujal [Here](https://github.com/spacesailor24/web3-3891-receipt) is a working example

**Comment by Spacesai1or** [comment]
Thank you for providing the test repo :heart: 

It looks like I received the tx hash using `web3@1.3.4`

![image](https://user-images.githubusercontent.com/20375610/106942242-8fbeee80-66e9-11eb-9cfc-59d7743c5538.png)

**Comment by imaksp** [comment]
> Thank you for providing the test repo :heart: 
> 
> It looks like I received the tx hash using `web3@1.3.4`
> 
> ![image](https://user-images.githubusercontent.com/20375610/106942242-8fbeee80-66e9-11eb-9cfc-59d7743c5538.png)
> 

Yes txHash is received but receipt is never received with 1.3.4 so loading never stops.

**Comment by Spacesai1or** [comment]
Oops I misread! @ujal said the tx hash was never received

I'll have to take a look at it further tomorrow morning, sorry for the inconvenience!

**Comment by imaksp** [comment]
Ok @ujal issue might be different but if you check code he posted, he is not listening for transactionHash event, so may be he didn't checked for it. I was also not listening for transactionHash event before as I can show success only after receipt is received & Receipt also has txHash, txHash event is added just for debugging purpose. Goal is to receive the receipt after transaction is confirmed on blockchain.

**Comment by Spacesai1or** [comment]
I updated my example repo above to include the `receipt` listeners [here](https://github.com/spacesailor24/web3-3891-receipt/blob/main/index.ts#L45)
Both `.on('receipt', receipt => {...})` and `.then(receipt => {...})` work, so my suspicion is a miscommunication between WalletConnect and Web3.js

**Comment by GregTheGreek** [comment]
@pedrouid can you see if `@walletconnect/web3-provider` is causing this issue?

**Comment by imaksp** [comment]
@spacesailor24 yes there must be some miscommunication but as it was working with web3 `1.2.11`, I have created an issue here.

**Comment by avinashbuddana** [comment]
it is perfectly working on version 1.2.11 .1.3 version has some issues in getting the receipt hook

**Comment by imaksp** [comment]
@spacesailor24 Hi, any update on this, are you sure its not a web3.js issue? if yes then why its working correctly with `1.2.11` ?

**Comment by StillFantastic** [comment]
My dapp also not getting a callback when connecting through WalletConnect, the web3 version we are using is 1.3.0

**Comment by clexmond** [comment]
I'm having the same issue (web3 `1.3.4`) while connecting with mobile MetaMask via WalletConnect and listening for events with https://web3js.readthedocs.io/en/v1.3.4/web3-eth-contract.html#contract-events. Works just fine with MetaMask extension in browser. I've confirmed Infura is setup correctly in the WalletConnect provider.

**Comment by clexmond** [comment]
> I'm having the same issue (web3 `1.3.4`) while connecting with mobile MetaMask via WalletConnect and listening for events with https://web3js.readthedocs.io/en/v1.3.4/web3-eth-contract.html#contract-events. Works just fine with MetaMask extension in browser. I've confirmed Infura is setup correctly in the WalletConnect provider.

I have since removed subscriptions as it seems they're not supported with WalletConnect's provider, but the issue remains.

**Comment by jeromevvb** [comment]
Same issue, using web3 1.3.4 cannot get callback. 
i tried all of the callback methods documented here: https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-send but any of them works.

**Comment by jeromevvb** [comment]
just installed web 1.3.5 and its working now. 
![4f5429df5ea6361fa8d3f08dfcdccdf9--programmer-humor-computer-engineering](https://user-images.githubusercontent.com/7522096/114539489-bddb2480-9c7e-11eb-876a-0c209532b702.jpeg)

this is my code by the way
```javascript
contract.methods
      .buy()
      .send({ from: wallet.address, value: ether })
      .on("transactionHash", (hash) => {
  

      })
      .catch(() => {
      
      });`

**Comment by imaksp** [comment]
@jeromevvb your code will work, transactionHash is being received in 1.3, but not receipt, I think you misread the issue.

**Comment by jeromevvb** [comment]
@aksdevac My Apologies, Indeed i misread the issue. I have the same issue also.

**Comment by hellwolf** [comment]
Hey guys, I did a comparison https://github.com/ChainSafe/web3.js/compare/v1.2.11..v1.3.0?diff=split

The biggest changeset I can suspect of is packages/web3-core-requestmanager/src/index.js

One thing caught my eyes is:

In 1.3.x code:

```
    if (this.provider.request) {
        const callbackRequest = callbackify(this.provider.request)
        const requestArgs = { method, params }
        callbackRequest(requestArgs, callback);
    }
```

In 1.2.x code:

```
        callbackify(this.provider.request.bind(this.provider))(payload, callback);
```

The missing of .bind may need some attention.

Although, I cannot yet confirm if the provider given by wallet-connect uses the `.request` variety

**Comment by hellwolf** [comment]
nevermind, https://github.com/aquiladev/wallet-connect-provider/blob/master/index.js shows it uses .send or .sendAsync

**Comment by hellwolf** [comment]
I have debugged into it and it boils down to that:

```
            _ethereumCall.subscribe('newBlockHeaders', function (err, blockHeader, sub) {
                if (err || !blockHeader) {
                    // fall back to polling
                    startInterval();
                } else {
                    checkConfirmation(existingReceipt, false, err, blockHeader, sub);
                }
            });
```

`newBlockHeaders` no longer received.

My test history:

* `1.3.0` - completely didn't work, some crashes
* `1.3.1` - worked
* `1.3.2` - worked
* `1.3.3` - stopped working

**Comment by hellwolf** [comment]
https://github.com/ChainSafe/web3.js/compare/v1.3.1..v1.3.2?diff=split

see changes in packages/web3-core-requestmanager/src/index.js



```
       if (typeof provider.request === 'function') { // EIP-1193 provider
            this.provider.on('message', function (payload) {
                if (payload && payload.type === 'eth_subscription' && payload.data) {
                    const data = payload.data
                    if (data.subscription && _this.subscriptions.has(data.subscription)) {
                        _this.subscriptions.get(data.subscription).callback(null, data.result);
                    }
                }
            })
        } else
```

**Comment by hellwolf** [comment]
I think this is the root cause

**Comment by hellwolf** [comment]
My temporary hack would be:

```
    wcProvider = new WalletConnectProvider({
      infuraId: process.env.REACT_APP_INFURA_ID,
    });
    delete wcProvider.__proto__.request;
    wcProvider.hasOwnProperty("request") && delete wcProvider.request;
```

;)

**Comment by stefanone91** [comment]
Same issue here.
Using web3 v1.3.x seems not working.
**Downgrading to 1.2.11** make my code working again.
The "receipt" event is called and so the async/await method is correctly resolved.

**Comment by dann254** [comment]
Same issue here.
Using web3 v1.3.x and v1.4.0

Just like the above comment 1.2.11 works. 

Also 1.5.0 doesn't work.

any solution?

**Comment by pedrouid** [comment]
Can you try the new WalletConnect provider?

```
npm install @walletconnect/ethereum-provider
```

Same API but different internals

**Comment by imaksp** [comment]
Hi, @pedrouid just tried with this new wc provider & web3 1.4.0, 1.3.4 still the same issue, here is the updated test app:
https://github.com/aksdevac/wc-web3-demo

**Comment by cg-gs** [comment]
@hellwolf 

Do you mind explaining your workaround?

**Comment by kytosai** [comment]
Have same issue with v1.5.x :( . I must install v1.2.11 to fix connect metamask app mobile with walletconnect to get callback success

**Comment by nazarhussain** [comment]
@aksdevac  I tried to reproduce it with the sample repo you provide. I tried version `1.2.11`, `1.4.0` and `1.5.2` with MetaMask iOS app. To me it was the same behaviour on all the versions. The event `transactionHash` was triggered but `receipt` was not triggered with any of the versions. Can you please verify once again by clearing all cache that is it really working on `1.2.11` as you described in the issue.

**Comment by nazarhussain** [comment]
I found the problem. :relieved: 

Its because of an assumption that if a provider specified an [`on handler`](https://github.com/ChainSafe/web3.js/blob/1547b18db217d0cc41077457c524a40ee89a8c03/packages/web3-core-method/src/index.js#L554) it MUST support `newBlockHeaders` event as well. In case of `@walletconnect/web3-provider` that’s not the case. If this happens to `@walletconnect/we3-provider` it can happen to other providers as well. The relevant code was tried to fine tune in following PR as well [PR-3517
](https://github.com/ChainSafe/web3.js/pull/3517/files)

I could not find any reference supporting this assumption. The [EIP-1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md) suggest that providers MUST be implementing `connect`, `disconnect` , `chainChanged`  , `accountsChanged`  and `message` but not forcing this for the support of subscriptions. e.g. We don't have support for subscriptions in the `web3-providers-http`. WalletConnect bridge provider supports [few events](https://docs.walletconnect.org/client-api#register-event-subscription) but not the `newBlockHeaders`.

And there is no standard way to identify if a provider is supporting particular subscription. Unless we have one, I think we should not be relying on the subscriptions for this particular flow of transactions receipt and confirmation and alway use the pooling technique.

**Comment by nazarhussain** [comment]
@jdevcs @spacesailor24 While I was testing the fix, I observed that bandwidth usage was increased for the app, which is obvious while checking for receipt with polling technique this will occur. I also thought the increased bandwidth usage may hinder many apps. What you guys think on it?

**Comment by wafflemakr** [comment]
Was having the same issue with web3 v1.5 (getting txHash but not receipt). Downgraded to 1.2.11 and now I get receipt. Using "@walletconnect/web3-provider": "^1.6.5"

**Comment by xale76** [comment]
even with 1.6.5 my code remains stuck in await.
in example:
await dai.methods.approve(icoquantix_address,amnt).send({from:address,type:type});

**Comment by xale76** [comment]
hello the problem is not resolved. In metamask on iPhone, no callback is issued

**Comment by aporo001** [comment]
why close this issue. I am having the same issue in version 1.6.0

**Comment by xale76** [comment]
> why close this issue. I am having the same issue in version 1.6.0
can you see the same problem as mine?
https://github.com/ChainSafe/web3.js/issues/4438#issue-1019870556

**Comment by xale76** [comment]
@spacesailor24 so my problem is fixed in v1.6.1-rc.0?

**Comment by Spacesai1or** [comment]
> @spacesailor24 so my problem is fixed in v1.6.1-rc.0?

@xale76 It should be, please test it and let us know!

**Comment by xale76** [comment]
@spacesailor24 it seems to work! great

**Comment by xale76** [comment]
@spacesailor24 can I use this version or it's better to wait next official release?

**Comment by Spacesai1or** [comment]
> @spacesailor24 can I use this version or it's better to wait next official release?
> 
> 

@xale76 It's an untested version, the official release won't be until after this week, but if it solves a problem for you, then it's at your discretion. Keep in mind you'll have to hardcode the RC version in your package.json (as you already have), and will have to revert the change when the official release comes out

**Comment by natansevero** [comment]
I was facing the same problem. I was using the `web3@1.5.1`. But the problem was solved when I upgraded version to `web3@1.6.1`

**Comment by BigMadCode** [comment]
I am still getting this issue on 1.7.0
Literally with wallet connect I am able to send a transaction and metamask processes it successfully but I get nothing back. Sometimes metamask throws an error "Oops something went wrong" but the transaction was confirmed. Is this Metamask or web3?

**Comment by 0xSzeth** [comment]
Bumping my web3 dependency to web3@1.7.3 fixed the issue for me
