### ISSUE TITLE
Embedding v0.18.0 blows up in Geth

### ISSUE THREAD

**Issue by karalabe** [ethereum/web3.js#543]
```
Fatal: Failed to start the JavaScript console: web3.js: ReferenceError: 'XMLHttpRequest' is not defined
```

**Comment by frozeman** [comment]
Could you give a line number?
Could your please clone web3.js, run `npm install` inside and then `npm script build` and try the resulting files in the dist folder?

The XMLHttpRequest is normally a standard in browsers and in node we include it using:
```
// browser
if (typeof window !== 'undefined' && window.XMLHttpRequest) {
    XMLHttpRequest = window.XMLHttpRequest; // jshint ignore: line
// node
} else {
    XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest; // jshint ignore: line
}
```

This is there since a while, the only addition is `xhr2`, which might cause this error, but please first try the above.

**Comment by karalabe** [comment]
I don't have a line number, the VM doesn't seem to return it. The js code also contains this:

```js
// go env doesn't have and need XMLHttpRequest
if (typeof XMLHttpRequest === 'undefined') {
    exports.XMLHttpRequest = {};
} else {
    exports.XMLHttpRequest = XMLHttpRequest; // jshint ignore:line
}
```

Perhaps something broke and this doesn't get executed any more?

**Comment by frozeman** [comment]
It could be XHR2, or the build has an error, thats why it would be good if you can rebuild on your side and try again.

**Comment by karalabe** [comment]
If I comment out https://github.com/ethereum/web3.js/blob/develop/dist/web3.js#L13452 the error doens't appear (of course I've no idea what commenting that line out does :P)

**Comment by frozeman** [comment]
Ok thats certainly from XHR2. So this is a problem then.

**Comment by frozeman** [comment]
The only solution i see, is to remove the timeout addition, using this library and publish a new version of web3.js.
Maybe i publish it as version 0.17.0 then.
How fast do you need this?

**Comment by karalabe** [comment]
a week :)

**Comment by frozeman** [comment]
I added it here: https://github.com/ethereum/web3.js/projects/1

**Comment by karalabe** [comment]
Fixed in 0.18.1.

**Comment by Dyrk** [comment]
@karalabe seems to be not fixed. I'm on 0.18.1 and I'm getting the same error.
The problem is that you use a strict mode and XMLHttpRequest is not declared with `var`.
This `var XMLHttpRequest` is commented out for some reason. When I uncommented it, the lib started working well serverside.
```
"use strict";

var errors = require('./errors');

// workaround to use httpprovider in different envs
var XMLHttpRequest; // jshint ignore: line

// browser
if (typeof window !== 'undefined' && window.XMLHttpRequest) {
    XMLHttpRequest = window.XMLHttpRequest; // jshint ignore: line
// node
} else {
    XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest; // jshint ignore: line
}
```
