### ISSUE TITLE
'npm i web3' results in error: "sh: 1: lerna: not found"

### ISSUE THREAD

**Issue by Tectract** [ethereum/web3.js#933]
Hi guys,

   I'm seeing failure and an error when I try to install the latest web3 via npm now, I became aware of this by some other students of solidity & web3 getting stuck on it and I recommended they actually roll back their version. What is "lerna"? I'm just here to report the bug, but this one does seem somewhat critical... Hopefully there's a quick fix?

action taken: 
`npm i -S web3`

error seen: 
```
> web3@1.0.0-beta.5 postinstall /home/thisUser/testing/node_modules/web3
> lerna bootstrap
sh: 1: lerna: not found
```
temporary workaround:
stick this line in your package.json file:
    "web3": "^0.18.4" 
under dependencies

**Comment by frozeman** [comment]
Should be fixed in beta.6

**Comment by Tectract** [comment]
Thanks!

**Comment by MichalZalecki** [comment]
@Tectract Is it working for you? I've tried beta.6 and beta.7 on node 7.10.0 and 8.1.4 and problem persists.

**Comment by Tectract** [comment]
Ugh, I have to update node? I thought they meant they were going to fix this in the next release of web3!

**Comment by MichalZalecki** [comment]
@Tectract Created a PR which should fix it and using it:

```
"web3": "github:MichalZalecki/web3.js#04dffef5c24fd9aebfc3aa8224a4f9d38ca69d68"
```
